### ISSUE TITLE
@StoredValue set(_ value: Item) not working as expected.

### ISSUE THREAD

**Issue by JaidynBluesky** [mergesort/Boutique#27]
Preface: we were chatting on Twitter yesterday about the .documentsDirectory issue.  I've switched to branch 2.0 and am trying some stuff out, so I understand the documentation isn't complete yet. :)

I have initialised a `@StoredValue` in one of my services like so:

```
@StoredValue<UserModel>(key: "User")
private var storedUser
```

where `UserModel` is `Codable`, `Equatable` and `Identifiable`.

From the existing file documentation, it seems like I just need to call

```
storedUser.set(newUser)
```

but that is giving me the following errors:

<img width="792" alt="Screen Shot 2022-08-02 at 10 48 34 am" src="https://user-images.githubusercontent.com/82005819/182281631-8b7c2389-89a9-43af-a736-92938bcd909d.png">

I've also tried awaiting the .set() function, but that doesn't solve it either.

Many thanks!

**Comment by mergesort** [comment]
Hey @JaidynBluesky! Your code is pretty close, instead of `storedUser.set(newUser)` you need to be calling `$storedUser.set(newUser)`. 

If you're familiar with property wrappers, the `wrappedValue` is an `Item`, but the `projectedValue` is a `StoredValue<Item>`. That means that when you access `storedUser` the item you're interacting with is of type `Item`, but the projected value is the one that contains all of the functions, including `set()` and `reset()`.

This follows similar conventions to `@Published var item: Item` would let you use `item` as a regular `Item`, but `$item` would project `AnyPublisher<Item, Never>`.

Hope that clears things and lemme know if it works! I'll make sure to add some documentation inline above the `set()` and `reset()` functions, and have taken a note down to explain this in the walkthrough for `@StoredValue`.

**Comment by JaidynBluesky** [comment]
Ah, that would be why it's not working! 😄

I'll give that a go.
