### ISSUE TITLE
Testing 3.0 — Store stops saving with no error when model changes

### ISSUE THREAD

**Issue by blainesolomon** [mergesort/Boutique#74]
Expected result: If the model is changed the schema updates/rewrites/overrides and continues to save using the latest model

Actual result: If the model is changed, the store silently fails to save changes between app launches

Workaround: Delete old store

**Comment by mergesort** [comment]
Hey @blainesolomon, thanks for giving Boutique 3.0 a shot! I want to make sure I understand the scenario correctly so please let me know if I'm answering the wrong question.

I assume the scenario is similar to this model below, where we have a `User` with this shape:
```swift
struct User {
    let id: UUID
    let name: String
}
```

Now we've updated the `User` model to add a non-optional property.
```swift
struct User {
    let id: UUID
    let name: String
    let isCat: Bool
}
```
> [!IMPORTANT]
> Emphasis on non-optional, because optional properties should decode the same way as the model without this new `isCat` property.

Since the models stored in Boutique will not have an `isCat` property, they will not decode properly into our new `User`, leading to the scenario you're describing in your report.

The rest of answer below assumes that this is the problem you're reporting.

---

Boutique doesn't have a built in way to know that the shape of the model has changed, it will only know that the shape of your models don't align. Deciphering the reason for the failure to decode would involve making assumptions about your desired model layout that I don't feel comfortable doing at the level Boutique operates at.

Instead though I think the correct solution is to run a migration when your model changes shape, modeled after (no pun intended) how database migrations are commonly performed in Core Data or server-side environments. To account for this workflow I've created a handy library called [Monarch](https://github.com/mergesort/Monarch), which allows you to run a migration whenever your model changes shape. When changing the shape of your model in an app update, what you would do is run a migration that sets a default value for that property, like this.

```swift
struct AddIsCatFieldMigration: Migration {
    static let id: MigrationID = "AddDefaultEmailMigration"

    @MigrationDependency private var usersController: UsersController

    func run() async throws {
        let users = self.usersController.users
        try await self.usersController.update(users.map { user in
            var updatedUser = user
            updatedUser.isCat = false
            return updatedUser
        })
    }
}
```

> [!NOTE]
> This is how I update the values in my app where I use controllers to manage data and state, there are numerous approaches you can take to do this so I don't mean this answer to be prescriptive.

This is the approach that I take in my apps, and have found it to be a successful tactic. This allows you to have full control over how you update models, which is important because there's no way for Boutique to know _why_ something failed to decode.

Separately, while this isn't the path that I go down in my own apps, if you'd like to bubble up errors whenever the models fail to load rather than silently returning an empty array, there is a throwing variant of the Store's initializer.

```swift
public init(storage: StorageEngine, cacheIdentifier: KeyPath<Item, String>) async throws
```

This initializer will allow you to know that the items in your Store failed to decode rather than receiving an empty array, without asserting any reason as to why that is the case.

Hope that helps, and if I didn't answer your question, do feel free to let me know!

**Comment by blainesolomon** [comment]
Absolutely amazing. 😍  Such a detailed easy to follow response. That's everything I needed.

**Comment by mergesort** [comment]
Im really happy that was helpful, thanks for letting me know!
